name: Build Geode Mod

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-modules:
    name: Update Modules
    runs-on: ubuntu-latest
    outputs:
      update-modules-status: ${{ steps.update-modules.outputs.status }}
    steps:
      - name: Update Repository
        id: update-modules
        run: |
          sudo apt-get update
          sudo apt-get install git
          git clone https://github.com/${{ github.repository }}.git
          cd geode-clicksound
          git config user.name "Clicks Submodule Updater"
          git config user.email github-actions@github.com
          git submodule update --remote --merge --verbose
          git add -A
          git commit -m "Update clicksounds/clicks module"
          git push
          echo "::set-output name=status::success"
  build:
    needs: ["update-modules"]
    if: needs.update-modules.outputs.update-modules-status == 'success' || needs.update-modules.outputs.update-modules-status != 'success'
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          
        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          sdk: nightly
          target: ${{ matrix.config.target }}
      
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build', 'update-modules']
    if: needs.update-modules.outputs.update-modules-status == 'success' || needs.update-modules.outputs.update-modules-status != 'success'

    steps:
      - uses: geode-sdk/build-geode-mod@combine
        id: build

      - uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
