name: Build Geode Mod

on:
  workflow_dispatch:
  push:

#concurrency:
#  group: build-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  update-modules:
    name: Update Modules
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Update Repository
        run: |
          git config user.name "Clicks Submodule Updater"
          git config user.email github-actions@github.com
          git submodules update
          add .
          git commit -m "Update clicksounds/clicks module"
          git push
  build:
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          
        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          sdk: nightly
          target: ${{ matrix.config.target }}
      
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - uses: geode-sdk/build-geode-mod@combine
        id: build

      - uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
