name: Rename All Sounds

on:
    workflow_dispatch:

jobs:
    rename:
      name: Rename Click Sounds
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Run Sounds Copier
          run: python ./.github/CopySoundsForRename.py
        - name: Run File Namer
          run: cd .github/FileNamer; python main.py
        - name: Upload sounds as an artifact
          uses: actions/upload-artifact@v3
          with:
            name: MultipleClick
            path: .github/FileNamer/Output
